spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ten
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 52530ed89d7a52ba7498aca9363f251e
            client-secret: WTTTgIfUM8MWsOvT8sF6Glet17DHLkSI
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

          naver:
            client-id: 네이버 클라이언트 ID
            client-secret: 네이버 클라이언트 Secret
            redirect-uri: http://localhost:8080/login/oauth2/code/naver (설정한 redirect URI)
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
           authorization_uri: https://nid.naver.com/oauth2.0/authorize
           token_uri: https://nid.naver.com/oauth2.0/token
           user-info-uri: https://openapi.naver.com/v1/nid/me
           user_name_attribute: response

  redis:
    host: localhost
    port: 6379



logging.level:
  org.hibernate.SQL: debug

jwt:
  secret-key: ItsveRy2loNgsecRetkeYOHmYgOd2bIgseCrEtKEySEcretK